version: 2
jobs:
  checkout:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths: .

  install:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v2-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v2-yarn-dependencies- # fallback to latest cache if no exact match is found
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v2-yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - .yarn-cache

  lint:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v2-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v2-yarn-dependencies- # fallback to latest cache if no exact match is found
      - run: yarn lint

  test:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v2-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v2-yarn-dependencies- # fallback to latest cache if no exact match is found
      - run: yarn zapier:test

  publish:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v2-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v2-yarn-dependencies- # fallback to latest cache if no exact match is found
      - run: echo '{"deployKey":"$ZAPIER_DEPLOY_KEY"}' > ~/.zapierrc && yarn zapier:push

tagged: &tagged
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

any: &any
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  build:
    jobs:
      - checkout:
          <<: *any
      - install:
          <<: *any
          requires:
            - checkout
      - lint:
          <<: *any
          requires:
            - install
      - test:
          <<: *any
          requires:
            - install
      - publish:
          <<: *tagged
          requires:
            - lint
            - test
